### ISSUE TITLE
Segfault with empty account no

### ISSUE THREAD

**Issue by Boldie** [monofox/python-aqbanking#9]
The lib will create a SEGFAULT if incorrect parameters were used. This shall be handled gracefully in a pythonic way.

```
Starting program: /usr/bin/python3 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aqbanking
>>> acc = aqbanking.Account(bank_code=10077777)
>>> acc.transactions()

Program received signal SIGSEGV, Segmentation fault.
0x0000000000543f84 in PyUnicode_AsUTF8AndSize ()
(gdb) bt
#0  0x0000000000543f84 in PyUnicode_AsUTF8AndSize ()
#1  0x00007ffff5eb565c in aqbanking_Account_transactions (self=0x7ffff674a660, args=0x7ffff7f79048, kwds=0x0) at aqbanking/aqbanking.cpp:778
#2  0x00000000004e9bc7 in PyCFunction_Call ()
#3  0x0000000000524414 in PyEval_EvalFrameEx ()
#4  0x000000000052d2e3 in ?? ()
#5  0x000000000052dfdf in PyEval_EvalCode ()
#6  0x00000000005fd2c2 in ?? ()
#7  0x00000000004583cd in PyRun_InteractiveOneObject ()
#8  0x0000000000458576 in PyRun_InteractiveLoopFlags ()
#9  0x00000000004585d0 in ?? ()
#10 0x00000000004cf26a in ?? ()
#11 0x00000000004cfe41 in main ()
(gdb) f 1
#1  0x00007ffff5eb565c in aqbanking_Account_transactions (self=0x7ffff674a660, args=0x7ffff7f79048, kwds=0x0) at aqbanking/aqbanking.cpp:778
778     aqbanking/aqbanking.cpp: No such file or directory.
(gdb) print self
$1 = (aqbanking_Account *) 0x7ffff674a660
(gdb) print self->no
$2 = (PyObject *) 0x0
```

**Comment by monofox** [comment]
I agree to you. Thanks for the information.
